# Generated by Django 5.2.10 on 2026-01-25 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("refund_due_soon", "Refund due soon"),
                            ("refund_overdue", "Refund overdue"),
                        ],
                        max_length=60,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Warning"), ("danger", "Danger")],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("entity_type", models.CharField(max_length=60)),
                ("entity_id", models.PositiveIntegerField()),
                ("message", models.CharField(max_length=240)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workspaces.workspace"
                    ),
                ),
            ],
        ),
    ]
