# Generated by Django 5.2.10 on 2026-01-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alert_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="type",
            field=models.CharField(
                choices=[
                    ("refund_due_soon", "Refund due soon"),
                    ("refund_at_risk", "Refund at risk"),
                    ("refund_overdue", "Refund overdue"),
                ],
                max_length=60,
            ),
        ),
    ]
