# Generated by Django 5.2.10 on 2026-01-25 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("type", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("ready", "Ready"), ("failed", "Failed")],
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workspaces.workspace"
                    ),
                ),
            ],
        ),
    ]
