# Generated by Django 5.2.10 on 2026-01-25 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "unique_together": {("workspace", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(default="shopify", max_length=30)),
                ("external_id", models.CharField(max_length=120)),
                ("amount", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="NGN", max_length=10)),
                ("status", models.CharField(default="unknown", max_length=30)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ops_refunds.customer",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "unique_together": {("workspace", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(default="stripe", max_length=30)),
                ("external_id", models.CharField(max_length=120)),
                ("amount", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="NGN", max_length=10)),
                ("status", models.CharField(default="unknown", max_length=30)),
                ("initiated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ops_refunds.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ops_refunds.order",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "unique_together": {("workspace", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(default="stripe", max_length=30)),
                ("external_id", models.CharField(max_length=120)),
                ("amount", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="NGN", max_length=10)),
                ("status", models.CharField(default="pending", max_length=30)),
                ("initiated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expected_by", models.DateTimeField(blank=True, null=True)),
                ("last_provider_update_at", models.DateTimeField(blank=True, null=True)),
                (
                    "risk_state",
                    models.CharField(
                        choices=[
                            ("SAFE", "Safe"),
                            ("DUE_SOON", "Due soon"),
                            ("AT_RISK", "At risk"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="SAFE",
                        max_length=20,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ops_refunds.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ops_refunds.order",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ops_refunds.paymenttransaction",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "unique_together": {("workspace", "external_id")},
            },
        ),
    ]
